version: '3.1'

networks:
  dbnet:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: testdb
    ports:
    - "5432:5432"
    networks:
    - dbnet
      
    